apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAiYXV0aCI6ICJRRk5vWVd4b2IyVnJlRHBuYUhCZlNGSmtOR0oyY3pOYVJGbzJTMXBYTTJOUE0yRnpjV0ppTWpCc1YxZEJNR1UxTmtaQyINCiAgICB9DQogIH0NCn0=
type: kubernetes.io/dockerconfigjson
